version: '3.8'
services:
  web:
    image: wordpress:5.4.1-php7.4-apache
    container_name: wordpress
    restart: always
    ports:
      - 8085:80
    depends_on:
      - db

  db:
    image: mariadb:10.4
    container_name: mariadb
    restart: always
    volumes:
      - db-volume:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: demowp
      MYSQL_USER: demowp
      MYSQL_PASSWORD: 123456
volumes:
  db-volume:
